// <auto-generated />
namespace Logic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class workerModelModified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workerModelModified));
        
        string IMigrationMetadata.Id
        {
            get { return "201810171148425_workerModelModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
