// <auto-generated />
namespace Logic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class worekr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(worekr));
        
        string IMigrationMetadata.Id
        {
            get { return "201810150732357_worekr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
